# Site
name: 'CryptoBuzz'
description: 'Curated list of cryptocurrency news'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
disqus: 'cryptobuzz'
email: 'f/mknyjnjl'
mailchimp-list: 'https://gmail.us14.list-manage.com/subscribe/post?u=ee32b064e0ed1537392ba0fc1&amp;id=af47b55cf8'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    gabriele:
      name:           Gabriele Picco
      site:           http://gabrielepicco.github.io/
      avatar:         https://gabrielepicco.github.io/assets/img/demo/avatar5.jpg
      bio:            "Passionate about Computer Science, Game development, Startups and Water Polo."
      twitter:        https://twitter.com/PiccoGabriele
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules, vendor]
