name: Produce and Consume

# Controls when the workflow will run
on:
  
  schedule:
  - cron: '0 0 */1 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  produce:
    runs-on: ubuntu-latest
    environment: alembik
    container:
      image: ghcr.io/gabrielepicco/alembik/alembik-producer
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.GHCR_TOKEN }}
      env:
        SOURCE: reddit
        SUBREDDIT: CryptoCurrency
        MONGO_HOST: ${{ secrets.MONGO_HOST }}
        MONGO_DB: alembik
        ITEM_TYPE: news
        USE_DEEP_LEARNING: true
    steps:
      - name: Download nltk lang
        working-directory: /app
        run: python -c "import nltk;nltk.download('punkt')"
      - name: Produce
        working-directory: /app
        run: python -m alembik
        
  consume-static-website:
   needs: produce
   runs-on: ubuntu-latest
   environment: alembik
   container:
     image: ghcr.io/lucacillario/alembik/alembik-instagram-consumer
     credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
     env:
       MONGO_HOST: ${{ secrets.MONGO_HOST }}
       MONGO_DB: alembik
       SOCIAL: static_website
       LOGGING_LEVEL: debug
       ACCOUNT: reddit-CryptoCurrency
   steps:
     - name: Consume static website
       working-directory: /app
       run: python -m alembik
       
  consume-twitter:
    needs: produce
    runs-on: ubuntu-latest
    environment: alembik
    container:
      image: ghcr.io/lucacillario/alembik/alembik-instagram-consumer
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.GHCR_TOKEN }}
      env:
        MONGO_HOST: ${{ secrets.MONGO_HOST }}
        MONGO_DB: alembik
        SOCIAL: twitter
        LOGGING_LEVEL: debug
        ACCOUNT: reddit-CryptoCurrency
    steps:
      - name: Consume twitter
        working-directory: /app
        run: python -m alembik
