name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 3.2
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.2
      - uses: helaili/jekyll-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          jekyll_build_options: "--config _config.yml,_config_base.yml"
