#name: Build and deploy Jekyll site to Netlify

#on:
#  push:
#    branches:
#      - main

#jobs:
#  netlify-pages:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: helaili/jekyll-action@v2
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          jekyll_build_options: "--config _config.yml,_config_base.yml"
#          target_branch: netlify-pages
